### ISSUE TITLE
As a user, I want a diagnosis condition to be affiliated to clinical practical guidance

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-guidelines#1]
The affiliation can be either automatic with a mouse over or via clickable external link

The clinical practice guideline can be internal hospital guidance on the intranet or external guidance (e.g. NICE guidance)

e.g. if diagnosis = tuberculosis, affiliation is to NICE TB practice guidelines

**Comment by davidmiller** [comment]
I think this is a custom Admin action.

e.g. As an admin, you add a Guideline, and you associate it with a particular diagnosis

**Comment by GabPoll** [comment]
Examples: (Diagnosis - link)
- Infective endocarditis - http://www.britishinfection.org/files/2714/1640/8773/Endocarditis_final_BSAC_2012.pdf
- pneumonia / LRTI - http://www.britishinfection.org/files/4114/1641/1014/thorax.pdf
- encephalitis - http://www.journalofinfection.com/article/S0163-4453%2811%2900563-9/pdf
- Clostridium difficile - https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/321891/Clostridium_difficile_management_and_treatment.pdf
- Tuberculosis - http://www.nice.org.uk/guidance/cg117/resources/guidance-tuberculosis-pdf
- Hepatitis B - http://www.nice.org.uk/guidance/cg165/resources/guidance-hepatitis-b-chronic-pdf

I could go on....

Worth noting that hospital-specific guidelines may trump these national guidelines, but links to both should be offered.

**Comment by GabPoll** [comment]
agree re custom admin.

**Comment by michaeledwardmarks** [comment]
@davidmiller
I see there are some commits on this front now - does that mean there is a test-version thing of this?

**Comment by GabPoll** [comment]
Very nice 1st pass @davidmiller 
@michaeledwardmarks try adding CAP as diagnosis to any patient

**Comment by davidmiller** [comment]
I think this is now ready for review ?

**Comment by GabPoll** [comment]
Review as in closure? I'd close it!

**Comment by michaeledwardmarks** [comment]
This is amazing!
