### ISSUE TITLE
Insert in Guideline modal heading the name of the diagnosis clicked on to bring up the guideline modal

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-guidelines#10]

**Comment by davidmiller** [comment]
Deployed !

**Comment by GabPoll** [comment]
Much better, thank you @davidmiller .

Going to be a nitpicker, sorry. Can we change "Select guideline for CAP" to "Guidelines for CAP" please?
Then can close.

**Comment by GabPoll** [comment]
Much better, thank you @davidmiller .

Going to be a nitpicker, sorry. Can we change "Select guideline for CAP" to "Guidelines for CAP" please?
Then can close.

**Comment by davidmiller** [comment]
Changed!

**Comment by GabPoll** [comment]
i feel better!
