### ISSUE TITLE
User specific data needs to be collected on usage of diagnosis associated guidelines

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-guidelines#3]
This is important for CPD purposes

**Comment by davidmiller** [comment]
What data do we want to collect ?

**Comment by GabPoll** [comment]
Click-through numbers sufficient in first instance.

**Comment by davidmiller** [comment]
See http://elcid04-test.herokuapp.com/adminguidelines/guidelineconsultation/

**Comment by GabPoll** [comment]
oh wow. Can that information be downloaded in CSV / txt file easily? If so, can easily close this as a first pass.

**Comment by davidmiller** [comment]
Not yet, but that's a v 0.2 thing IMHO. 
I can run a query and answer arbitrary questions.

Exporting the data is another User need ! 

Writing an export interface can naturally be done.
Would like to do some more work fixing main extract before adding any new extract interfaces though - hence not _right_ now

**Comment by GabPoll** [comment]
Ok, running a one-off query perhaps in 6 months, that's fine.
Will see re exporting data and if people are interested in long run. They should be but may not be! ;)
