### ISSUE TITLE
Guideline modal columns wrong way round

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-guidelines#6]
I think Name & Source the wrong way round

**Comment by davidmiller** [comment]
Right you are !

**Comment by davidmiller** [comment]
Fixed & deployed !

**Comment by GabPoll** [comment]
I take responsibility - it's not quite right. The column names and content now match. However, I think I would swap columns round, so that you have name first then source (reading from left to right).

Sorry for nitpicking again. It is fab, i promise

**Comment by davidmiller** [comment]
Swapped !

**Comment by GabPoll** [comment]
much better, thank yoy @davidmiller

**Comment by davidmiller** [comment]
NP - it's just another example of my instincts not being correct for the way real users think...

That's exactly why we have you && @michaeledwardmarks involved in the process !
