### ISSUE TITLE
Guideline modal has one extra column

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-guidelines#7]
Don't need the far right or far left one, unless you were planning some kind of hover preview window. I think opening in a new tab is sufficient and probably easiest.

**Comment by davidmiller** [comment]
So, that column is intended to show what kind of guideline this is.

e.g. are you linking to an intranet page, NICE.org.uk, a PDF file.

May well not be required.

Thoughts @michaeledwardmarks @drcjar  ?

**Comment by michaeledwardmarks** [comment]
Probably unnecessary

**Comment by davidmiller** [comment]
Removed !

**Comment by GabPoll** [comment]
Better without, thank you.
