### ISSUE TITLE
Move guideline modal so that underlying diagnosis is still visible

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-guidelines#9]
Helps continuity.

In general modal can be smaller, prob narrower too.

**Comment by davidmiller** [comment]
@GabPoll I think you mean: 

> As a Doctor
> I want to see the underlying diagnosis when reviewing guidelines
> So that I maintain the context of the current action I'm performing, and I know I'm in the right place

It's one of the cases where stating the user need helps us to _pick_ solutions :) 

For info: 

Moving the modal and making sure it never covers the diagnosis is really quite complicated.

Including a line of text in the modal or it's heading that says something like "Guidelines for CAP" is really simple.

**Comment by davidmiller** [comment]
In general, separate issues for separate issues, but: re. size, lots of the guideline titles you sent me are really long - hence the wide modal - try throwing a bunch in and you'll see what I mean.

**Comment by GabPoll** [comment]
Happy to be corrected!
The alternative solution I'd also considered and I'd be happy with.

**Comment by davidmiller** [comment]
Let's make sure that we meet that need before closing though ! ;)

**Comment by davidmiller** [comment]
Right - that's what #10 is about !

**Comment by GabPoll** [comment]
clarified and simpler in #10
